name: tfm-variantes
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - fastqc
  - multiqc
  - trim-galore
  - bwa-mem2
  - samtools
  - gatk4
  - ensembl-vep
  - bcftools
  - bedtools
  - sra-tools
  - scikit-learn
  - xgboost
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - imbalanced-learn
  - pip
  - pip:
    - crossmap
